import React from "react";
import Footer3 from "../footer/Footer3";
import Header from "../header/Header";
import useBodyClass from "../../hooks/useBodyClass";
import Head from "next/head";

function Layout({ children, pageTitle }) {
  useBodyClass("home-dark2");

  return (
    <>
      <Head>
        <title>{pageTitle ? `${pageTitle} | EVD Technology` : "EVD Technology"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/img/fevicon.jpg" />
      </Head>
      <Header />
      {children}
      <Footer3 />
    </>
  );
}

export default Layout;
